### ISSUE TITLE
Demo - Release - Sharp from S3 Layer

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#147]
# Tasks
- [ ] Deploy Sharp layer for private use
- [ ] Remove Sharp modules from .zip lambdas
- [ ] Ensure that Sharp layer is mounted and usable by `serverless-nextjs-demo`

# Background Info
- Next.js apps need Sharp for Linux not Sharp for Mac
- With Docker, this works by running `npm i sharp` inside of a Docker container
- With .zip Lambdas it is necessary to build a layer on Linux, push to S3, then add that Layer to the Lambda functions
- Here is where the layer exists: https://github.com/zoellner/sharp-heic-lambda-layer

**Comment by huntharo** [comment]
The Sharp layer has been published.  This remains to be tested.
