### ISSUE TITLE
Demo - Complete the Release Console App

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#2]
# Overview
- Complete the Release Console app
- Managed in [huntharo/microapps-app-release](https://github.com/huntharo/microapps-app-release)

# To-Do

- [x] Fetch Apps list on startup
- [x] Put Apps list into a grid
- [x] Create a selected item event for the grid
- [x] Fetch Versions and Rules for one app when an app is selected
- [x] Populate the retrieved Versions and Rules into two new grids
- [x] Handle selection changes of the Application
- [x] Allow editing of default rule to select a version
