### ISSUE TITLE
v0.3 - OIDC / OAuth for CloudFront

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#227]
## To-Do
- [x] Allow passing additional edge lambdas to `MicroApps` construct
- [x] Pass auth lambda in private deploy
- [x] Add auth lambda to static routes in private deploys
- [x] Confirm auth works in dev/qa/prod
- [x] Fix redirect using state
- [ ] Fix refresh to not logout
- [x] Add token redirect endpoint
- [x] Evaluate `auth.js` as option

## Overview
- Need Lambda Authorizer integration for PwrDrvr internal applications
- Authorizer demo will be beneficial to consumers of microapps-core
- OIDC is preferred as it is generally much easier to setup, but SAML is acceptable if no other option can work
- Federation between Cognito and Google appears to be possible, but potentially as a social login with a domain restriction and not as an App integration in Google Workspace directly (actually it's not clear if social login is possible for a Workspace domain)

## Documentation
- Authorization Code Flow RFC
  - https://www.rfc-editor.org/rfc/rfc6749#section-4.1
- Okta Sample Lambda Node.js OAuth Integration
  - https://github.com/oktadev/okta-nodejs-aws-lambda-example
- Sample implementation from Auth.js
  - https://authjs.dev/
  - Concerns
    - Does not use a DB persisted nonce to avoid replay attacks
    - Sends the refresh token to the browser - not clear if this encrypted
- OAuth Threat Models RFC
  - https://datatracker.ietf.org/doc/rfc6819/
- Nonce and State
  - https://medium.com/@benjamin.botto/oauth-replay-attack-mitigation-18655a62fe53
- One Login Examples / Code - Useful for pointers on OIDC
  - https://github.com/onelogin/lambda_authorizor_demo
  - https://developers.onelogin.com/api-authorization/authorizing-aws-api-gateway-requests-with-onelogin-oauth-access-tokens
- Using Google as a Social Provider for AWS Cognito User Pools
  - [Set Up Google as a social identity provider in an Amazon Cognito user pool](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/)
- Cognito with External Identity Provider
  - https://github.com/aws-samples/amazon-cognito-example-for-external-idp
- SAML for Serverless Apps - 2017
  - [SAML for Your Serverless JavaScript Application: Part II | AWS Compute Blog (amazon.com)](https://aws.amazon.com/blogs/compute/saml-for-your-serverless-javascript-application-part-ii/)
- Open Banking OIDC Example
  - [aws-samples/openbanking-brazilian-auth-samples (github.com)](https://github.com/aws-samples/openbanking-brazilian-auth-samples)
- Google Workspace OIDC Support Added
  - [Google Workspace expands identity services](https://workspace.google.com/learn-more/gsuite-expands-identity-services.html)
- Google Identity Platform for Work
  - [Google Identity  |  Google Developers](https://developers.google.com/identity/#identity-platform-for-work)
- Google Identity API OpenID Connect Setup (OIDC)
  - [OpenID Connect  |  Google Identity  |  Google Developers](https://developers.google.com/identity/protocols/oauth2/openid-connect)

**Comment by huntharo** [comment]
Remaining work to publish this as a construct moved to #304
