### ISSUE TITLE
v0.3 - Cross Account Deployments

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#253]
## Motivations
- Larger organizations will have single CloudFront distributions with different dev teams deploying apps into different AWS accounts
- MicroApps needs the ability to register child account Lambdas on a parent account CloudFront / MicroApps deploy

## To-Do
- [x] Split Lambda and DynamoDB access into two different DeployerSvc requests
- [x] Update `microapps-publish` to detect and use the new style when it is supported
- [x] Setup GHPublicChild account for cross account testing
- [x] Create Child account CDK construct
- [x] Create Child account CDK stack
- [x] Add parameters to Parent account construct / stack to allow child account DeployerSvc to invoke
- [x] CI - Add Child account CDK stack deployment
- [x] CI - Add Child account deploy of `child-demo` app
- [x] Test and confirm that `child-demo` app appears in Release app and that app invoke works
- [x] Address inevitable issues with edge-to-origin request signing - Most likely there will be a problem with the target account or region being passed to the signing functions
- [x] Fix colliding names for the `edge-role` child stack for the `basic` and `basic-prefix` stacks
- [x] Fix registration of child account permission to invoke parent account deployer

## Design

- DeployerSvc
  - Add a stub version of this that invokes the Deployer in the primary account
    - This Deployer stub should grant the API Gateway in the primary account permission to invoke the lambda in the secondary account
- `microapps-publish`
  - Add any parameters needed to publish to another account?
  - This can probably be handled with no parameters as the Deployer lambda can return the necessary config info
- Apps from multiple accounts can all be served from a single prefix

### Request Dispatch

![MicroApps - Architecture](https://user-images.githubusercontent.com/5617868/211132720-604510fa-de44-4ac6-a79b-c28c829d2490.png)

### Deployment

![Image](https://user-images.githubusercontent.com/5617868/210928443-9f090d3f-9145-4c88-9bcd-18fc178b4dac.png)

**Comment by huntharo** [comment]
The base work for this is done but proving that this sorts of deployments work remains to be completed

**Comment by huntharo** [comment]
Stacks are created, CI is updated, manually adding the edge to origin arn to the resource policy of the demo-app alias allows this to work, but the edge to origin role arn export is not yet working
