### ISSUE TITLE
Move static file routing to Lambda @ Edge

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#264]
# Motivations
- Static files, or things that look like static files, are served by some app frameworks
- URL-type apps may need static files forwarded to the URL origin
- Makes it so that more things will "just work"

# To-Do
- [x] Explore Origin Groups to route 404s on S3 to the Lambda origin
- [ ] Add setting for `static files on S3` - Default to true, allow to be set to false for a version
- [ ] Set the `authMethod` field on the `origin` to `origin-access-identity`
- [ ] Move the API Gateway endpoint to the lambda config file
- [x] Switch the origin for API Gateway behaviors to S3 - This is required because an OAI is needed but an OAI cannot be added when changing from a Custom origin to an S3 origin, only when the default origin is already an S3 origin
- [ ] Lookup in the Lambda @ Edge if the static files should be forwarded to the origin or not
- [ ] Allow the static file route to be removed from the CDK stack, falling through to Lambda @ Edge
- [ ] When static files are not on S3, route them to the app, otherwise route them to S3

# Proposed Request Routing to S3 and Lambda

## 2nd Proposal

![Image](https://user-images.githubusercontent.com/5617868/222913451-0e6ed906-b6ee-461f-99a7-61db13135ce1.png)

## Rejected - 1st Proposal - Can't work because Origin Groups only Support GET/HEAD/OPTIONS

![MicroApps - Architecture - Request Routing](https://user-images.githubusercontent.com/5617868/222905777-dcfd49b1-5d41-4c98-a552-8213983a3299.png)

# Docs

## Changing Custom Origin to S3 Origin

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-content-based-S3-origin-based-on-query

## Changing S3 Origin to Custom Origin

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-content-based-custom-origin-request-trigger

## Changing S3 Origin Region

https://aws.amazon.com/blogs/networking-and-content-delivery/using-amazon-cloudfront-and-amazon-s3-to-build-multi-region-active-active-geo-proximity-applications/

**Comment by huntharo** [comment]
With Origin Groups the OriginRequest function can run twice.  Need to detect whether this is the primary (should rewrite and sign for Function URL) or fallback origin (should not touch the request and let it fall through to S3 with OAI signing).

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/high_availability_origin_failover.html#concept_origin_groups.lambda


![Image](https://user-images.githubusercontent.com/5617868/222149699-581e8d0b-7088-4103-8981-f159b71a2dff.png)
