### ISSUE TITLE
v0.3 - URL App Type

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#268]
## Motivations
- Need to allow some existing apps to be hosted on the same URL to get features like login

## Docs
- VPC Link for Private API Gateway integrations: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-private.html
- PrivateLink for calling private API Gateway: https://aws.amazon.com/blogs/compute/architecture-patterns-for-consuming-private-apis-cross-account/

## To-Do
- [ ] microapps-publish
       - [ ] Add `-t` option for `url` - Forwards from Edge function to the URL with signing
       - [ ] Add `-t` option for `url-signed` - Forwards from Edge function to the API Gateway w/Sigv4 signing, then API Gateway forwards to the URL (API Gateway in this case is not managed by MicroApps as it requires VPC connectivity that is an exercise for the reader)
- [ ] deployer-svc
        - [ ] Handle the new types and writing info about them to the DB
- [ ] edge-to-origin
       - [ ] Ability to forward to signed or unsigned `url` apps
       - [ ] Handle the type names
       - [ ] Optionally forward all static file requests to S3
- [ ] Does not need a version, but a version can be used to store the info and to change that info by publishing another version (e.g. to switch to a new URL origin)
- [ ] Can use a version, particularly when forwarding static files to S3, which may need new versions published with each app update (or can use a single version and "overwrite" to just accumulate all the files into a single version directory)
