### ISSUE TITLE
v0.3 - Fix appFrame.html copy outside of repo

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#274]
## Motivations
- Build is failing for usage of the CDK construct outside of the repo
  - https://github.com/pwrdrvr/microapps-pwrdrvr/actions/runs/3410992007/jobs/5674861391

## To-Do
- [x] Fix appFrame.html copy
- [ ] Add test to microapps-core repo that will catch this failure?
- [x] Publish v0.3.2-alpha.1
- [x] Test in private repo
- [ ] Publish v0.3.2

**Comment by huntharo** [comment]
Original issue resolved, new issue uncovered:

```
2022-12-30T20:05:54.013Z	fba15f33-863c-4c34-b9ac-103b1d764081	ERROR	
{
    "_logLevel": "error",
    "msg": "unexpected exception - returning 599",
    "statusCode": 599,
    "error": {
        "name": "ValidationException",
        "message": "1 validation error detected: Value '${Token[TOKEN.397]}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+",
        "stack": "ValidationException: 1 validation error detected: Value '${Token[TOKEN.397]}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+\n    at Jre (/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2074:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n    at /node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\n    at CT.retry (/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at /node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n    at /node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/QueryCommand.js:34:26\n    at Function.LoadVersions (/microapps-datalib/src/models/version.ts:112:23)\n    at async Promise.all (index 0)\n    at Function.GetVersionsAndRules (/microapps-datalib/src/models/application.ts:54:5)",
        "$fault": "client",
        "$metadata": {
            "httpStatusCode": 400,
            "requestId": "27BRIB58SBD2VUF85CLGFCHUN3VV4KQNSO5AEMVJF66Q9ASUAAJG",
            "attempts": 1,
            "totalRetryDelay": 0
        },
        "__type": "com.amazon.coral.validate#ValidationException"
    },
    "_tags": []
}
```

**Comment by huntharo** [comment]
Fixed by #275
