### ISSUE TITLE
v0.3 - publish/deployer - Allow passing Lambda Version or Alias and skipping related steps

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#290]
## Motivations

- Early versions created the version/alias in the deployer only because I did not know (or it maybe wasn't possible at the time) how to create a Version or Alias reliably in CDK
- Now it's quite easy to create a version in a CDK-deployed Lambda function and only when the code changes
- Most users should be creating their own versions
- Some users will also assign their own aliases
- The publish/deployer tools can just detect whether they were passed a version or alias and skip the related steps

## To-Do

- [x] microapps-publish - check for version or alias ARN
- [x] microapps-publish - if version, skip version step
- [x] microapps-publish - if alias, skip version and alias steps
- [x] publish tool - update documentation to indicate that this can be a version or an alias and the suggestion is for it to be a version (let microapps create the alias with the function url configured with IAM)
