### ISSUE TITLE
v0.3 - Make API Gateway optional

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#291]
## Motivations
- CDK support for HTTP API Gateways is currently alpha
- The new Lambda Function URL support is currently all that is used
- Removing deploy of API Gateway now would speed up deploys

## To-Do
- [x] Make API Gateway optional in all CDK constructs
- [x] Allow the API Gateway Origin to be missing on the CloudFront distribution
- [x] Use S3 as the default Origin on CloudFront
- [x] Add support to change the S3 Origin to a Custom Origin (Lambda etc)
~~- [ ] Move `MicroAppsAPIGwy` into it's own CDK Construct~~
~~- [ ] Remove API Gateway as an option from the `MicroApps` CDK Construct~~
~~- [ ] Remove the API Gateway npm modules for CDK from the microapps-cdk package~~
~~- [ ] Do not publish the API Gateway CDK Construct for now~~
~~- [ ] Publish the updated MicroApps construct~~

Items moved to #293 for moving the support into a new module in next minor version.
