### ISSUE TITLE
Edge - Simplify Routes

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#306]
## Motivations
- There are way too many routes
- These are not all strictly necessary anymore

## To-Do
- [ ] Determine which routes can be cleaned up or consolidated before moving static file routing to the Origin Request function
- [ ] Implement the cleanups from above
- [ ] Determine if another route of cleanups can be made after static file routing is moved to the Origin Request function
