### ISSUE TITLE
Documentation - Revamp README.md

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#308]
## Motivations
- The project has completely evolved from the original documentation, most of which no longer applies
- The project has reached a useful state and should be documented to attract usage

## To-Do
- [ ] Create `docs` directory
- [ ] Focus the primary `README.md` on: problem being solved, unique features / benefits, architecture overviews, and videos demonstrating usage
- [ ] Link out to additional documentation for:
        - [ ] How to deploy the infrastructure
        - [ ] How to deploy first app
        - [ ] Advanced routing features

**Comment by huntharo** [comment]
A portion of this was handled in #312 cleanups to the README
