### ISSUE TITLE
microapps-publish - Naming and convenience packages

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#336]
## Motivations
- The project should be easy to find
- The name should be unique
- The commands should be memorable and short

## To-Do
- [ ] Publish `pwrdrvr` top-level package that includes `@pwrdrvr/microapps-publish` as a dependency
- [ ] Add command called `pwrdrvr` to `@pwrdrvr/microapps-publish` package
- [ ] Update docs to refer to `pwrdrvr` command instead of `microapps-publish`
